import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import AppName from "../../components/auth/AppName";
import AuthBackground from "../../components/auth/AuthBackground";
import AuthContainer from "../../components/auth/AuthContainer";
import AuthErrorMessage from "../../components/auth/AuthErrorMessage";
import NewPasswordForm from "../../components/auth/resetPassword/NewPasswordForm";
import SkipButton from "../../components/auth/SkipButton";
import { GetServerSideProps } from "next";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";

export const getServerSideProps: GetServerSideProps = async (context) => {
   const supabase = createServerSupabaseClient(context);
   const { data } = await supabase.auth.getSession();
   if (data.session) {
      return {
         redirect: {
            destination: "/",
            permanent: false,
         },
      };
   }

   return {
      props: {},
   };
};

export default function ResetPassword({}: any) {
   const [showResetPage, setShowResetPage] = useState<boolean>(false);
   const [error, setError] = useState<string | null>(null);
   const supabaseClient = useSupabaseClient();
   const router = useRouter();

   useEffect(() => {
      supabaseClient.auth.onAuthStateChange((event) => {
         if (event === "PASSWORD_RECOVERY") setShowResetPage(true);
      });
   }, []);

   useEffect(() => {
      const handleRouteChange = () => supabaseClient.auth.signOut();
      router.events.on("routeChangeStart", handleRouteChange);
      return () => router.events.off("routeChangeStart", handleRouteChange);
   }, []);

   const newPasswordHandler = async (values: any) => {
      const { password } = values;
      const { error } = await supabaseClient.auth.updateUser({
         password,
      });
      if (error) setError(error.message);
   };

   if (!showResetPage) {
      return (
         <div className="h-screen w-full bg-dark-bg-primary text-dark-text-hard grid place-content-center">
            <div>Loading...</div>
         </div>
      );
   }
   return (
      <div className="relative overflow-hidden">
         <Head>
            <title>Reset Password</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <AuthBackground />
         <AuthContainer setError={setError}>
            <AppName />
            <div className="text-light-text-normal">Type your new password</div>
            <NewPasswordForm submitHandler={newPasswordHandler} />
            <SkipButton reset />
         </AuthContainer>
         <AuthErrorMessage error={error} setError={setError} />
      </div>
   );
}
