import Head from "next/head";
import { useState } from "react";
import DeleteListModal from "../../components/manage/DeleteListModal";
import ListCard from "../../components/manage/ListCard";
import PageTitle from "../../components/PageTitle";
import useListsContext from "../../context/ListsContext";
import ListModel from "../../models/listModel";

export default function Lists() {
   const { lists } = useListsContext();
   const [listToDelete, setListToDelete] = useState<ListModel | null>(null);

   const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
   const openDeleteModal = (list: any) => {
      setIsModalOpen(true);
      setListToDelete(list);
   };
   const closeDeleteModal = () => {
      setIsModalOpen(false);
      setListToDelete(null);
   };

   return (
      <>
         <Head>
            <title>Manage Lists</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <PageTitle>Manage</PageTitle>
         <div className="grid grid-cols-1 lg:grid-cols-2 gap-y-8 gap-x-5 2xl:px-20">
            {lists.map((list) => (
               <ListCard
                  key={list.id}
                  list={list}
                  openDeleteModal={openDeleteModal}
               />
            ))}
         </div>
         <DeleteListModal
            isOpen={isModalOpen}
            close={closeDeleteModal}
            listToDelete={listToDelete}
         />
      </>
   );
}
