const SM_MEDIA_QUERY = 640;
const MD_MEDIA_QUERY = 768;
const LG_MEDIA_QUERY = 1024;
const XL_MEDIA_QUERY = 1280;
const XXL_MEDIA_QUERY = 1536;

export {
   SM_MEDIA_QUERY,
   MD_MEDIA_QUERY,
   LG_MEDIA_QUERY,
   XL_MEDIA_QUERY,
   XXL_MEDIA_QUERY,
};
