import { AnimatePresence, motion } from "framer-motion";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Card from "../components/card/Card";

import PageTitle from "../components/PageTitle";
import PageAnimationContainer from "../containers/PageAnimationContainer";
import usePageLoadingContext from "../context/PageLoadingContext";

export const getServerSideProps: GetServerSideProps = async (context) => {
   const { type } = context.query;
   const mediaType = type === "tv" ? "tv" : "movie";
   return {
      props: { mediaType },
   };
};

interface Props {
   mediaType: "tv" | "movie";
}

export default function Popular({ mediaType }: Props) {
   const router = useRouter();

   const [media, setMedia] = useState<any[]>([]);
   const { setIsLoading } = usePageLoadingContext();

   useEffect(() => {
      const getData = async () => {
         const res = await fetch(`/api/popular/${mediaType}/1`);
         const data = await res.json();
         console.log(data.results);
         setMedia(data.results);
         setIsLoading(false);
      };
      getData();
   }, [mediaType, setIsLoading]);

   return (
      <PageAnimationContainer>
         <Head>
            <title>Popular</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <PageTitle>Popular</PageTitle>
         <AnimatePresence
            mode="wait"
            onExitComplete={() => {
               const container = document.getElementById("scroll-container")!;
               container.scrollTo({ top: 0 });
            }}
         >
            <motion.div
               initial={{ y: 100, opacity: 0 }}
               animate={{ y: 0, opacity: 1 }}
               exit={{ y: 100, opacity: 0 }}
               transition={{ duration: 0.5, ease: "easeInOut" }}
               key={router.asPath}
               className="grid grid-cols-4 2xl:grid-cols-5 gap-5 overflow-hidden"
            >
               {media.map((media) => (
                  <Card key={media.id} media={media} />
               ))}
            </motion.div>
         </AnimatePresence>
      </PageAnimationContainer>
   );
}
