import Head from "next/head";

import useRemoveBackgroundImage from "@/hooks/useRemoveBackgroundImage";
import Title from "@/components/Title";

import { AnimatePresence, motion } from "framer-motion";
import MainCards from "@/features/searchCards/components/MainCards";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import DiscoverFilter from "@/features/discover/components/DiscoverFilter";
import DiscoverInitialText from "@/features/discover/components/DiscoverInitialText";

export default function Discover() {
   useRemoveBackgroundImage();

   const [apiUrl, setApiUrl] = useState<string | null>(null);

   const router = useRouter();
   const { asPath, query } = router;

   useEffect(() => {
      const { media_type } = query;
      if (media_type) {
         let filters = "";
         Object.keys(query).forEach((key) => {
            if (query[key] && key !== "media_type") {
               filters += `&${key}=${query[key]}`;
            }
         });
         setApiUrl(`/discover/${media_type}/${filters}`);
      } else {
         setApiUrl(null);
      }
   }, [asPath, query]);
   return (
      <div className="overflow-x-hidden">
         <Head>
            <title>Discover</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="relative w-full">
            <Title title="Discover">
               <DiscoverFilter />
            </Title>
         </div>
         <motion.div exit={{ opacity: 0, transition: { duration: 0.4 } }}>
            <AnimatePresence mode="wait">
               {apiUrl ? (
                  <MainCards
                     key={asPath}
                     mediaType={query.media_type as "tv" | "movie"}
                     apiUrl={apiUrl}
                  />
               ) : (
                  <DiscoverInitialText />
               )}
            </AnimatePresence>
         </motion.div>
      </div>
   );
}
