import Head from "next/head";

import useRemoveBackgroundImage from "@/hooks/useRemoveBackgroundImage";
import Title from "@/components/Title";

import DiscoverFilter from "@/components/Pages/Discover/DiscoverFilter";
import InitialText from "@/components/Pages/Discover/InitialText";
import { AnimatePresence, motion } from "framer-motion";
import MainCards from "@/features/searchCards/components/MainCards";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Discover() {
   useRemoveBackgroundImage();

   const [apiUrl, setApiUrl] = useState<string | null>(null);

   const router = useRouter();
   const { asPath, query } = router;

   useEffect(() => {
      const { media_type } = query;
      const filters = "";
      if (media_type) {
         setApiUrl(`/discover/${media_type}/${filters}`);
      } else {
         setApiUrl(null);
      }
   }, [asPath]);

   return (
      <div className="">
         <Head>
            <title>Discover</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="relative w-full">
            <Title title="Discover">
               <DiscoverFilter />
            </Title>
         </div>
         <motion.div exit={{ opacity: 0, transition: { duration: 0.4 } }}>
            <AnimatePresence mode="wait">
               {apiUrl ? (
                  <MainCards
                     key={asPath}
                     mediaType={query.media_type as "tv" | "movie"}
                     apiUrl={apiUrl}
                  />
               ) : (
                  <InitialText />
               )}
            </AnimatePresence>
         </motion.div>
      </div>
   );
}
