const RATING_GLOBAL_MIN = 0;
const RATING_GLOBAL_MAX = 10;
const DURATION_GLOBAL_MIN = 0;
const DURATION_GLOBAL_MAX = 400;

export {
   RATING_GLOBAL_MIN,
   RATING_GLOBAL_MAX,
   DURATION_GLOBAL_MIN,
   DURATION_GLOBAL_MAX,
};
